spike/SC-1517
epcpower/st pull request #49
Opened 2024-05-02 17:12 UTC by abnepc

## Jira Story
[SC-1517](https://epcpower.atlassian.net/browse/SC-1517)
## About
Investigate/remove `sunspecdemo` from the repo
## Associated Pull Requests
* [stlib]()
* [st]()
* [pm]()
* [grid-tied]()
* [rm-dc]()
* [m-pm]()
* [m-bcu]()
* [m-tcu]()
## Reproduction Steps
N/A
## Validation
Delete your `.venv` folder and do a `poetry install`. Then make sure that `sunspecdemo` was not installed. 

[SC-1517]: https://epcpower.atlassian.net/browse/SC-1517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-05-08 17:02 UTC, abnepc commented on .vscode/settings.json
> +  "conventionalCommits.scopes": ["SC-1517"]
[1bb6251](https://github.com/epcpower/st/pull/49/commits/1bb625123da0e3109112a7c584edcbd30d626f18) & [ee7f81e](https://github.com/epcpower/st/pull/49/commits/ee7f81e3f7d0d51d0e7ecdfa280c7da65b50f790)

2024-05-08 17:02 UTC, abnepc commented on pyproject.toml
> +build-backend = "poetry.core.masonry.api"
[58eb2fc](https://github.com/epcpower/st/pull/49/commits/58eb2fc8fe3d1decab7b1622223d945cdc3fb0ae)

2024-05-23 17:24 UTC, gordon-epc requested changes

2024-05-23 17:24 UTC, gordon-epc commented on pyproject.toml
> +pyinstaller-hooks-contrib = "2022.10"
```suggestion
pyinstaller-hooks-contrib = "2022.10"  # Locks the version to avoid updating during `poetry update`
```

2024-05-23 18:41 UTC, abnepc commented on pyproject.toml
> +pyinstaller-hooks-contrib = "2022.10"
[1f48722](https://github.com/epcpower/st/pull/49/commits/1f48722e35ba51a422748e703d35da42e25b3c46)

2024-05-31 22:40 UTC, gordon-epc approved these changes

2024-06-04 15:35 UTC, merged